# Generated by Django 3.0.8 on 2020-07-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200712_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=225),
        ),
    ]
